### PR TITLE
Change color to indicate mic level while recording

### PR DESCRIPTION
**Pull request by ijc8**
This PR provides some visual feedback to indicate whether the mic is working! :microphone: :100: 

Note that this avoids showing [sound waves](https://www.todepond.com/report/arroost/#:~:text=sound%20waves); it just shows the mic's current level while recording.

Demo with mic working & not (unmute to hear my beautiful voice):

https://github.com/user-attachments/assets/0d741c44-2920-460f-a4ec-e9d7157085d4

Inspired by [this moment](https://www.youtube.com/live/4GOeYylCMJI?si=llDb8IVtPVJXkJF2&t=12992) at LIVE (in which it wasn't clear that there were mic issues until *after* recording) and ensuing discussion.

### CODE REVIEW

**Comment by TodePond** [comment]
that's great thank you!

happy to merge as is, but one thing I'm thinking is: appearing red "immediately" (even if you aren't speaking) can be a fun moment because it makes you go "oh shit it's recording", so i wonder if the visual could be "red as default" and then it does something else when it picks up volume or something. not sure. 

the default red also communicates to the user that it might be recording.

not sure what the solution is so if there isn't an obvious one i'll merge in a day or two and create an issue

**Comment by TodePond** [comment]
@allcontributors please add @ijc8 for code and design

**Comment by ijc8** [comment]
How's this?

https://github.com/user-attachments/assets/58882f5c-679f-474c-89c0-9165334ec2ad

**Comment by TodePond** [comment]
love it

also you should totes post those two videos on masto! people would love to see the behind the scenes of the change :)

**Pull request merged**
