### PR TITLE
The video is out! 🎉 

### PR DESCRIPTION
**Pull request by evoL**
This updates the README to reflect the new reality in which 🎵 **Arrows in Arrows in Arrows** is out on YouTube. (yay!)

### CODE REVIEW

**Comment by mahdoosh1** [comment]
uhhh
didnt you put link at top?
like other repos?

**Comment by evoL** [comment]
The link pointed to the teaser video, so I changed it to the final video.

Thanks for pointing out the other repos! I changed the phrasing to make it closer.

**Comment by TodePond** [comment]
thanks!

**Comment by TodePond** [comment]
@all-contributors please add @evoL for documentation

**Pull request merged**
